### ISSUE TITLE
feat: 서버 연결 작업

### ISSUE THREAD

**Issue by juno7803** [SOPT-28/brunch-front#8]
### Todo
- [x] axios `client.js` 파일 생성하여 axios instance 만들기
- [x] `.env` 파일로 baseURL 관리하기
- [x] swr 혹은 recoil atom을 이용하여 상태관리 하기
